#!/usr/bin/env python3
"""Upload a new novel to lyriq.space R2 bucket.

Usage: python3 upload_novel.py --id N --dir <slug>
Requires R2 env vars: R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY, R2_ENDPOINT, R2_BUCKET

Each chapter gets a 'highlight' field (本章金句/Chapter Highlight) generated by
an LLM before upload, so highlights are ready on day one.
"""
import json, os, re, sys, time, yaml
from pathlib import Path
import boto3, urllib.request

NOVELS_DIR = Path("/root/novels")
ENV_FILE = Path("/root/novel-site/.env")
R2_PUBLIC = "https://data.lyriq.space"
BOOKS_KEY = "books.json"

# --- .env loader (safe — avoids source .env pollution) ---
def load_env(env_file=ENV_FILE):
    """Read .env key=value pairs. Skips comments and shell code blocks."""
    env = {}
    with open(env_file) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#') or line.startswith('$('):
                continue
            if '=' in line:
                k, v = line.split('=', 1)
                k, v = k.strip(), v.strip()
                if k.isidentifier() and not k.startswith('__'):
                    env[k] = v
    os.environ.update(env)

# --- Tag auto-mapping ---
_SYNONYM_MAP = {
    "Fantasy":      ["fantasy", "dark fantasy", "urban fantasy", "werewolf", "litrpg", "eldritch", "vampire", "cozy fantasy", "gothic"],
    "Romance":      ["romance", "monster romance", "stalker romance", "dark romance", "sweet pet", "harem", "love triangle", "enemies-to-lovers", "exes-to-lovers", "lovers"],
    "Sci-Fi":       ["sci-fi", "scifi", "science fiction", "cyberpunk", "cyber", "tech thriller", "tech-thriller"],
    "Thriller":     ["thriller", "political thriller", "tech thriller", "cyber thriller", "psychological thriller", "psychological horror", "horror", "mystery", "suspense", "gaslighting", "booktok"],
    "Dystopia":     ["dystopia", "dystopian", "post-apocalyptic", "apocalyptic"],
    "Dark Academia":["dark academia"],
    "Contemporary": ["contemporary", "satire", "dark comedy"],
    "Queer":        ["sapphic", "queer", "lgbtq", "gender fluid"],
    "Female Lead":  ["female lead", "female protagonist", "female empowerment", "feminism", "feminist"],
}

def genre_to_tags(genre_str, data=None):
    data = data or {}
    meta = data.get("meta", data)
    classif = data.get("classification", {})
    all_text = (genre_str or "").lower()
    # Normalize hyphenated keywords so "dark-academia" matches "dark academia"
    all_text = all_text.replace('-', ' ')
    for key in ("subgenre", "subgenres"):
        for src in (data, meta, classif):
            val = src.get(key)
            if isinstance(val, list): all_text += " " + " ".join(val).lower()
            elif isinstance(val, str): all_text += " " + val.lower()
    tags = []
    for tag, keywords in _SYNONYM_MAP.items():
        if any(kw in all_text for kw in keywords):
            tags.append(tag)
    return sorted(tags)
# --- YAML parsing ---
# Supports TWO novel-project.yaml layouts:
#   Layout A (flat/meta): meta: {title, author, genre, language}, premise: "..."
#   Layout B (nested):    project: {title, author}, classification: {genre, subgenres}, premise: "..."
def parse_yaml(dir_path):
    yaml_file = dir_path / "novel-project.yaml"
    if not yaml_file.exists():
        raise FileNotFoundError(f"No novel-project.yaml in {dir_path}")
    with open(yaml_file, encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    # Layout A: meta wrapper
    meta = data.get("meta", data)
    # Layout B: project + classification wrappers (GlitterAndGuilt style)
    proj = data.get("project", {})
    classif = data.get("classification", {})
    for key in list(data.keys()):
        if key[0].isupper() and key.lower() not in data:
            data[key.lower()] = data[key]
    meta_lower = {k.lower(): v for k, v in meta.items()}
    proj_lower = {k.lower(): v for k, v in proj.items()}
    # Title/author: prefer project (Layout B), then meta (Layout A), then top-level
    # Also fall back to `name` field (some YAMLs use `name:` instead of `title:`)
    title = proj_lower.get("title", meta_lower.get("title", data.get("title", data.get("name", "Untitled"))))
    author = proj_lower.get("author", meta_lower.get("author", data.get("author", "Unknown")))
    # Genre: prefer classification (Layout B), then meta (Layout A), then top-level
    genre = classif.get("genre", meta_lower.get("genre", data.get("genre", "")))
    # Language: check all levels, default to english if missing (most novels are English)
    lang = (meta_lower.get("language") or classif.get("language") or
            data.get("language") or "english")
    lang = lang.lower()
    if lang == "en": lang = "english"
    # Intro fallback chain: premise → pitch → logline → core_conflict → conflict → summary → tagline → synopsis → description → ch001 excerpt
    intro = ""
    for src in [data, meta_lower]:
        for field in ["premise", "pitch", "logline", "core_conflict", "conflict", "summary", "tagline", "synopsis", "description"]:
            val = src.get(field, "")
            if val and isinstance(val, str):
                intro = val[:200]
                break
        if intro: break
    if not intro:
        # Last resort: read first chapter and use opening paragraph
        ch_dir = dir_path / "chapters"
        ch_files = sorted(ch_dir.glob("ch001.md")) if ch_dir.exists() else []
        if not ch_files:
            ch_files = sorted((dir_path).glob("ch001.md"))
        if ch_files:
            with open(ch_files[0], encoding="utf-8") as f:
                paras = [p.strip() for p in f.read().split("\n\n")
                         if p.strip() and not p.strip().startswith("#")]
            if paras:
                intro = paras[0][:200]
    tags = genre_to_tags(genre, {**data, **classif})
    return {"title": title, "author": author, "genre": genre, "lang": lang,
            "tags": tags, "intro": intro}

# --- Chapter title normalization ---
_WORD_MAP = {
    'One':1,'Two':2,'Three':3,'Four':4,'Five':5,'Six':6,'Seven':7,'Eight':8,'Nine':9,'Ten':10,
    'Eleven':11,'Twelve':12,'Thirteen':13,'Fourteen':14,'Fifteen':15,'Sixteen':16,'Seventeen':17,
    'Eighteen':18,'Nineteen':19,'Twenty':20,'Thirty':30,'Forty':40,'Fifty':50,'Sixty':60,
    'Seventy':70,'Eighty':80,'Ninety':90,
}
_WORD_NUM_RE = re.compile(r'^Chapter\s+([A-Z][a-z]+(?:-[A-Z][a-z]+)*):')

def _word_to_num(s):
    """Convert 'Thirty-Two' or 'Seven' to integer, or None if not a recognized word-number."""
    total = 0
    for part in s.split('-'):
        val = _WORD_MAP.get(part)
        if val is None:
            return None
        if val >= 20:
            total += val
        else:
            total += val  # ones or teens: just add
    return total if total > 0 else None

def normalize_chapter_title(title):
    """Normalize chapter title: word-numbers -> digits; em/en/hyphen dash -> colon."""
    # Convert word-numbers like "Chapter Thirty-Two: ..."
    m = _WORD_NUM_RE.match(title)
    if m:
        num = _word_to_num(m.group(1))
        if num is not None:
            title = f"Chapter {num}:{title[m.end():]}"
    # Normalize dash separators "Chapter N — Title" / "Chapter N - Title" -> "Chapter N: Title"
    title = re.sub(r'^(Chapter\s+\d+)\s*[—–-]\s*', r'\1: ', title)
    return title

# --- Chapter parsing ---
def parse_chapter(text):
    lines = text.strip().split("\n")
    title = lines[0].lstrip("# ").strip() if lines and lines[0].startswith("#") else f"Chapter"
    # If H1 has no subtitle (just "Chapter N" or "Chapter One"), check for H2 subtitle
    is_bare_chapter = bool(re.match(r'^Chapter\s+\d+$', title) or
                            re.match(r'^Chapter\s+[A-Z][a-z]+(?:-[A-Z][a-z]+)*$', title))
    if is_bare_chapter and len(lines) > 1:
        for line in lines[1:]:
            if line.startswith("## "):
                subtitle = line.lstrip("# ").strip()
                # Skip section markers like "I", "II", "1", "Part One"
                if re.match(r'^(?:[IVXLC]+|\d+|[A-Z]\.?|Part\s+\w+)$', subtitle, re.IGNORECASE):
                    continue
                title = f"{title}: {subtitle}"
                break
    paragraphs = [p.strip() for p in text.split("\n\n") if p.strip() and not p.strip().startswith("#")]
    return title, paragraphs

def get_chapter_files(dir_path):
    ch_dir = dir_path / "chapters"
    if not ch_dir.exists():
        ch_dir = dir_path
    return sorted(ch_dir.glob("ch*.md"))

def chapter_id_from_name(f):
    m = re.search(r'ch(\d+)', f.name)
    return int(m.group(1)) if m else 0
# --- R2 helpers ---
def get_r2_client():
    key = os.environ.get("R2_ACCESS_KEY_ID", "")
    if len(key) < 32:
        raise ValueError(f"R2_ACCESS_KEY_ID too short ({len(key)} chars, need 32)")
    return boto3.client("s3",
        endpoint_url=os.environ["R2_ENDPOINT"],
        aws_access_key_id=key,
        aws_secret_access_key=os.environ["R2_SECRET_ACCESS_KEY"],
    )

def download_books_from_r2(client):
    bucket = os.environ.get("R2_BUCKET", "novel-data")
    try:
        obj = client.get_object(Bucket=bucket, Key=BOOKS_KEY)
        return json.loads(obj["Body"].read())
    except client.exceptions.NoSuchKey:
        return []

def upload_to_r2(client, key, data_bytes, content_type="application/json", cache_control=None):
    bucket = os.environ.get("R2_BUCKET", "novel-data")
    cc = cache_control or "public, max-age=31536000, immutable"
    client.put_object(Bucket=bucket, Key=key,
        Body=data_bytes, ContentType=content_type,
        CacheControl=cc)

# --- Highlight generation (inline LLM call) ---
def get_llm_config():
    """Read LLM base_url, api_key, default model from hermes config.yaml."""
    import yaml as _yaml
    with open('/root/.hermes/config.yaml') as f:
        cfg = _yaml.safe_load(f)
    m = cfg.get('model', {})
    return m.get('base_url', ''), m.get('api_key', ''), m.get('default', '')

def generate_highlight(title, content_text, lang='en',
                       model=None, api_base=None, api_key=None):
    """Call LLM to generate a one-line chapter highlight / 本章金句."""
    if not api_base or not api_key:
        api_base, api_key, _ = get_llm_config()
    model = model or os.environ.get('HL_MODEL', 'Qwen/Qwen3-32B')

    # Truncate content for context window efficiency
    text = content_text[:5000]
    if len(content_text) > 5000:
        text += '...'

    if lang == 'zh' or any('\u4e00' <= c <= '\u9fff' for c in title):
        prompt = f"""你是小说精读编辑。请为以下章节生成一句"本章金句"或"核心悬念"。

要求：
- 一句话，不超过40个中文字
- 要抓眼球、勾起阅读欲望
- 可以是原文中的精彩句子，也可以是你提炼的悬念摘要
- 不要用引号包裹

章节标题：{title}
章节正文：
{text}"""
    else:
        prompt = f"""You are a masterful book editor. Generate a single compelling "chapter highlight" line for this novel chapter.

Rules:
- One sentence, max 25 words
- Must be eye-catching and hook the reader's curiosity
- Can be a striking quote from the text OR a teasing summary of the core suspense
- Do NOT wrap in quotes
- Do NOT start with "In this chapter" or similar meta-language

Chapter title: {title}
Chapter text:
{text}"""

    body = json.dumps({
        'model': model,
        'messages': [{'role': 'user', 'content': prompt}],
        'max_tokens': 60,
        'temperature': 0.7
    }).encode()

    req = urllib.request.Request(
        f'{api_base}/chat/completions',
        data=body,
        headers={
            'Content-Type': 'application/json',
            'Authorization': f'Bearer {api_key}',
        }
    )
    try:
        with urllib.request.urlopen(req, timeout=180) as resp:
            result = json.loads(resp.read())
        highlight = result['choices'][0]['message']['content'].strip().strip('"').strip("'")
        # Strip LLM-generated meta prefixes (本章金句, 核心悬念, etc.)
        highlight = re.sub(r'^(?:本章金句|核心悬念)[：:]\s*', '', highlight).strip()
        # Strip trailing meta-commentary in Chinese brackets
        highlight = re.sub(r'\n*（[^）]*(?:解析|提炼|凝练|说明|备注|注)[^）]*）$', '', highlight, flags=re.DOTALL).strip()
        return highlight
    except Exception as e:
        print(f'  [LLM ERROR] {e}')
        return None

# --- Main pipeline ---
def slugify(text):
    """Normalize slug to lowercase kebab-case.

    Must match the frontend seo.ts slugify() behavior for findBookBySlug() to work.
    Key rule: lowercase kebab-case, only [a-z0-9-], no leading/trailing/consecutive hyphens.
    Note: we replace & with 'and' before normalizing, which is more readable than
    the frontend's raw [^a-z0-9] replacement (would turn & into a hyphen). This is
    safe because the frontend slugify also lowercases, so 'hex-and-order' matches.
    """
    trimmed = text.strip()
    if re.match(r'^[a-z0-9]+(?:-[a-z0-9]+)*$', trimmed):
        return trimmed
    s = trimmed.replace('&', 'and')
    s = re.sub(r'([a-z0-9])([A-Z])', r'\1-\2', s)
    s = s.lower()
    s = re.sub(r'[^a-z0-9]+', '-', s)
    s = re.sub(r'^-+|-+$', '', s)
    s = re.sub(r'-+', '-', s)
    return s or 'untitled'

def upload_novel(book_id, dir_name, skip_highlights=False, hl_model=None):
    # Normalize slug to lowercase kebab-case for URL routing (must match frontend seo.ts slugify)
    slug = slugify(dir_name)
    dir_path = NOVELS_DIR / dir_name
    if not dir_path.exists():
        # Try slugified name as fallback
        dir_path = NOVELS_DIR / slug
        if not dir_path.exists():
            raise FileNotFoundError(f"Novel dir not found: tried {dir_name} and {slug}")
    meta = parse_yaml(dir_path)
    chapter_files = get_chapter_files(dir_path)
    
    client = get_r2_client()
    
    # LLM config for highlight generation
    hl_api_base, hl_api_key, _ = ('', '', '') if skip_highlights else get_llm_config()
    lang_code = 'zh' if meta['lang'] not in ('english', 'en') else 'en'
    hl_ok = hl_fail = 0
    
    # Generate chapter JSONs
    catalog_chapters = []
    for f in chapter_files:
        ch_id = chapter_id_from_name(f)
        if ch_id == 0: continue
        with open(f, encoding="utf-8") as fh:
            ch_title, paragraphs = parse_chapter(fh.read())
        # Normalize: "Chapter Thirty-Two: ..." → "Chapter 32: ..."
        ch_title = normalize_chapter_title(ch_title)
        # Inject "Chapter N:" prefix if missing (some md files omit it)
        if not re.match(r'^Chapter\s+\d+', ch_title):
            ch_title = f"Chapter {ch_id}: {ch_title}"
        catalog_chapters.append({"chapter_id": ch_id, "title": ch_title})
        
        # Generate highlight via LLM before upload
        highlight = ""
        if not skip_highlights and hl_api_base:
            content_text = "\n\n".join(paragraphs)
            if len(content_text.strip()) >= 50:
                # Retry with exponential backoff (same as generate_highlights.py)
                backoff = 5
                for attempt in range(3):
                    print(f'  Ch {ch_id}: generating highlight...', end=' ', flush=True)
                    highlight = generate_highlight(
                        ch_title, content_text, lang_code,
                        model=hl_model, api_base=hl_api_base, api_key=hl_api_key)
                    if highlight:
                        hl_ok += 1
                        print(f'✅ {highlight[:60]}')
                        break
                    if attempt < 2:
                        print(f'RETRY ({attempt+1}/2, wait {backoff}s)')
                        time.sleep(backoff)
                        backoff *= 2
                if not highlight:
                    print(f'  Ch {ch_id}: highlight FAILED after 3 attempts')
                    hl_fail += 1
                    highlight = ""
                time.sleep(0.5)  # Rate limit
        
        ch_obj = {"book_id": book_id, "chapter_id": ch_id,
                  "title": ch_title, "content": paragraphs}
        if highlight:
            ch_obj["highlight"] = highlight
        ch_data = json.dumps(ch_obj, ensure_ascii=False)
        upload_to_r2(client, f"{book_id}/{ch_id}.json", ch_data.encode())
    
    # Generate catalog
    catalog = json.dumps({"book_id": book_id, "chapters": catalog_chapters}, ensure_ascii=False)
    upload_to_r2(client, f"catalog_{book_id}.json", catalog.encode())
    
    # Update books.json
    books = download_books_from_r2(client)
    if any(b["id"] == book_id for b in books):
        books = [b for b in books if b["id"] != book_id]
    books.append({"id": book_id, "slug": slug, "title": meta["title"],
        "author": meta["author"], "category": meta["genre"],
        "intro": meta["intro"], "total_chapters": len(catalog_chapters),
        "lang": meta["lang"], "tags": meta["tags"]})
    books.sort(key=lambda b: b["id"])
    # Upload books.json with no-cache to prevent stale CDN copies
    books_json_bytes = json.dumps(books, ensure_ascii=False, indent=2).encode()
    upload_to_r2(client, BOOKS_KEY, books_json_bytes,
                 content_type="application/json",
                 cache_control="no-cache, no-store, must-revalidate")
    
    print(f"✅ Uploaded book {book_id}: {meta['title']} ({len(catalog_chapters)} chapters)")
    print(f"   lang={meta['lang']}, tags={meta['tags']}")
    if not skip_highlights:
        print(f"   highlights: {hl_ok} generated, {hl_fail} failed")
    return books

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--id", type=int, required=True)
    parser.add_argument("--dir", required=True)
    parser.add_argument("--skip-highlights", action="store_true",
                        help="Skip LLM highlight generation (faster upload)")
    parser.add_argument("--hl-model", type=str, default=None,
                        help="Override LLM model for highlights (default: Qwen/Qwen3-32B)")
    args = parser.parse_args()
    load_env()  # Load .env safely before any R2/CF operations
    book_id = args.id
    dir_name = args.dir
    books = upload_novel(book_id, dir_name,
                         skip_highlights=args.skip_highlights,
                         hl_model=args.hl_model)
